name: Terraform CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group rg-aks-multiregion --name aks-us --overwrite-existing

      - name: Get LoadBalancer IP
        id: lb
        run: |
          chmod +x scripts/get_lb_ip.sh
          OUTPUT=$(./scripts/get_lb_ip.sh)
          echo "$OUTPUT"
          echo "$OUTPUT" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "us_endpoint=${{ env.LB_IP }}" -var "ind_endpoint=${{ env.LB_IP }}" -var "aus_endpoint=${{ env.LB_IP }}"
